version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: usflanelinha-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: usflanelinha-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
